// AUTO-GENERATED by scripts/generate-latest-videos.mjs
// Source DB: ../Discord Agent/data/state.db
// Generated at: 2026-07-08T20:28:42.657Z

export type MoonshotVideo = {
  id: string
  title: string
  url: string
  embedUrl: string
  postedAt: string
  guid: string
}

export const latestMoonshotVideos: MoonshotVideo[] = [
  {
    "id": "XCunMF6frio",
    "title": "Fable 5 Is Back & Govt-Leashed, Altman Offers 5% of OpenAI & AI Grows Conscious | #269",
    "url": "https://www.youtube.com/watch?v=XCunMF6frio",
    "embedUrl": "https://www.youtube.com/embed/XCunMF6frio",
    "postedAt": "2026-07-08T20:28:41.481180+00:00",
    "guid": "youtube:XCunMF6frio"
  },
  {
    "id": "XjOLz--C_nQ",
    "title": "Sonnet 5 Drops, China’s $4,900 Robot, Fusion’s First Plant Gets Licensed W/ Philip Johnston | #268",
    "url": "https://www.youtube.com/watch?v=XjOLz--C_nQ",
    "embedUrl": "https://www.youtube.com/embed/XjOLz--C_nQ",
    "postedAt": "2026-07-01T20:58:41.826265+00:00",
    "guid": "youtube:XjOLz--C_nQ"
  },
  {
    "id": "ZDKwsDavHCY",
    "title": "Dave Blundin: Who I Am & What I Believe | Meet the Mates (Bonus Episode)",
    "url": "https://www.youtube.com/watch?v=ZDKwsDavHCY",
    "embedUrl": "https://www.youtube.com/embed/ZDKwsDavHCY",
    "postedAt": "2026-07-01T15:29:13.879941+00:00",
    "guid": "youtube:ZDKwsDavHCY"
  },
  {
    "id": "-H7J_-zr7pA",
    "title": "Anthropic vs. Alibaba, OpenAI Delays Its IPO, and the US Government Blocks GPT-5.6 | #267",
    "url": "https://www.youtube.com/watch?v=-H7J_-zr7pA",
    "embedUrl": "https://www.youtube.com/embed/-H7J_-zr7pA",
    "postedAt": "2026-06-29T20:28:44.434824+00:00",
    "guid": "youtube:-H7J_-zr7pA"
  },
  {
    "id": "kPSLLeccrik",
    "title": "The $10B Satellite Empire Putting AI in Orbit, Why Chips Beat Rockets & China's #1 Open Model | #266",
    "url": "https://www.youtube.com/watch?v=kPSLLeccrik",
    "embedUrl": "https://www.youtube.com/embed/kPSLLeccrik",
    "postedAt": "2026-06-26T15:28:58.147310+00:00",
    "guid": "youtube:kPSLLeccrik"
  }
]

export const latestMoonshotVideosGeneratedAt = "2026-07-08T20:28:42.657Z"
