// AUTO-GENERATED by scripts/generate-latest-videos.mjs
// Source DB: ../Discord Agent/data/state.db
// Generated at: 2026-09-28T20:52:52.611Z

export type MoonshotVideo = {
  id: string
  title: string
  url: string
  embedUrl: string
  postedAt: string
  guid: string
}

export const latestMoonshotVideos: MoonshotVideo[] = [
  {
    "id": "ZOhUSIaa2MA",
    "title": "We Gave Away $2,000,000 To 5 AI Builders | MOONSHOTS Live",
    "url": "https://www.youtube.com/watch?v=ZOhUSIaa2MA",
    "embedUrl": "https://www.youtube.com/embed/ZOhUSIaa2MA",
    "postedAt": "2026-09-28T20:52:51.839357+00:00",
    "guid": "youtube:ZOhUSIaa2MA"
  },
  {
    "id": "_8pHsq0YoNE",
    "title": "Why We Gave Away $3,500,000.00 for Someone to Build the Next Star Trek | Moonshots Live",
    "url": "https://www.youtube.com/watch?v=_8pHsq0YoNE",
    "embedUrl": "https://www.youtube.com/embed/_8pHsq0YoNE",
    "postedAt": "2026-09-28T20:22:58.114580+00:00",
    "guid": "youtube:_8pHsq0YoNE"
  },
  {
    "id": "wRY9XCrT0eg",
    "title": "Palmer Luckey: Autonomous Weapons Are Ancient and Why Anduril Won't Build Humanoids | EP #295",
    "url": "https://www.youtube.com/watch?v=wRY9XCrT0eg",
    "embedUrl": "https://www.youtube.com/embed/wRY9XCrT0eg",
    "postedAt": "2026-09-28T15:22:57.852713+00:00",
    "guid": "youtube:wRY9XCrT0eg"
  },
  {
    "id": "Cbk7hdOwJj4",
    "title": "Jensen Pushes Back on Doomers, Xi & Trump Talk AI, and “AI” Gets a Rebrand | #294 MOONSHOTS Live",
    "url": "https://www.youtube.com/watch?v=Cbk7hdOwJj4",
    "embedUrl": "https://www.youtube.com/embed/Cbk7hdOwJj4",
    "postedAt": "2026-09-27T15:23:04.426716+00:00",
    "guid": "youtube:Cbk7hdOwJj4"
  },
  {
    "id": "s5BFumpCH_Q",
    "title": "Ask the Mates Anything Round #2 | MOONSHOTS AMA  #293",
    "url": "https://www.youtube.com/watch?v=s5BFumpCH_Q",
    "embedUrl": "https://www.youtube.com/embed/s5BFumpCH_Q",
    "postedAt": "2026-09-22T20:23:00.091537+00:00",
    "guid": "youtube:s5BFumpCH_Q"
  }
]

export const latestMoonshotVideosGeneratedAt = "2026-09-28T20:52:52.611Z"
