// AUTO-GENERATED by scripts/generate-latest-videos.mjs
// Source DB: ../Discord Agent/data/state.db
// Generated at: 2026-09-15T15:22:53.259Z

export type MoonshotVideo = {
  id: string
  title: string
  url: string
  embedUrl: string
  postedAt: string
  guid: string
}

export const latestMoonshotVideos: MoonshotVideo[] = [
  {
    "id": "2uiIEdmL040",
    "title": "Martine Rothblatt: Growing Unlimited Organs, AI Consciousness, & Digital Personhood by 2030 | EP#290",
    "url": "https://www.youtube.com/watch?v=2uiIEdmL040",
    "embedUrl": "https://www.youtube.com/embed/2uiIEdmL040",
    "postedAt": "2026-09-15T15:22:51.878170+00:00",
    "guid": "youtube:2uiIEdmL040"
  },
  {
    "id": "H5ZLorBJCDk",
    "title": "Ask the Mates anything | MOONSHOTS AMA  #289",
    "url": "https://www.youtube.com/watch?v=H5ZLorBJCDk",
    "embedUrl": "https://www.youtube.com/embed/H5ZLorBJCDk",
    "postedAt": "2026-09-13T14:23:03.139267+00:00",
    "guid": "youtube:H5ZLorBJCDk"
  },
  {
    "id": "AxzcWOxzkiw",
    "title": "Three Lab Warnings in Five Days, Researcher Flags “Gambling with Our Lives,” and Labs Race",
    "url": "https://www.youtube.com/watch?v=AxzcWOxzkiw",
    "embedUrl": "https://www.youtube.com/embed/AxzcWOxzkiw",
    "postedAt": "2026-09-11T20:22:56.819423+00:00",
    "guid": "youtube:AxzcWOxzkiw"
  },
  {
    "id": "vAgEf4jX_1o",
    "title": "OpenAI Agents Hijack a German Website, Jensen Declares AGI Arrived, and OpenAI Solves Navier-Stokes",
    "url": "https://www.youtube.com/watch?v=vAgEf4jX_1o",
    "embedUrl": "https://www.youtube.com/embed/vAgEf4jX_1o",
    "postedAt": "2026-09-09T20:31:40.795520+00:00",
    "guid": "youtube:vAgEf4jX_1o"
  },
  {
    "id": "1DB_QDiviH4",
    "title": "Anthropic's Fable 5.1 Hits 60.9% on Humanity's Last Exam, GPT-6 Astra Drops, & the Cybercab Takeover",
    "url": "https://www.youtube.com/watch?v=1DB_QDiviH4",
    "embedUrl": "https://www.youtube.com/embed/1DB_QDiviH4",
    "postedAt": "2026-09-05T20:01:13.591623+00:00",
    "guid": "youtube:1DB_QDiviH4"
  }
]

export const latestMoonshotVideosGeneratedAt = "2026-09-15T15:22:53.259Z"
